name: lang_tr
description: "LangTr is a Flutter generator package designed to simplify the management of translation files in your Flutter applications"
version: 0.0.1+1
homepage: https://github.com/D3R50N/lang_tr.git

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
